timezone: Fix clang operator precedence warning
clang issues:

zdump.c:669:7: error: operator '?:' has lower precedence than '&'; '&'
will be evaluated first [-Werror,-Wbitwise-conditional-parentheses]
                    ? (delta(&tm, &lotm) == t - lot

which is exactly what the code intendes.  Instead of adding a
warning suppress, place parentheses around the '&' expression.